from typing import List, Optional, Protocol, Any
from uuid import UUID
from dmesh.sdk.models import DataProduct, DataContract

class DataProductRepository(Protocol):
    async def get(self, id: UUID) -> DataProduct: ...
    async def save(self, product: DataProduct) -> None: ...
    async def list(self, domain: Optional[str] = None, name: Optional[str] = None) -> List[DataProduct]: ...
    async def delete(self, id: UUID) -> bool: ...

class DataContractRepository(Protocol):
    async def get(self, id: UUID) -> DataContract: ...
    async def save(self, contract: DataContract) -> None: ...
    async def list(self, dp_id: Optional[str] = None) -> List[DataContract]: ...
    async def delete(self, id: UUID) -> bool: ...
