from typing import List, Optional, Protocol, Any
from uuid import UUID
from dmesh.sdk.models import DataProduct, DataContract

class DataProductRepository(Protocol):
    async def get(self, id: UUID) -> DataProduct: ...
    async def save(self, product: DataProduct) -> None: ...
    async def list(self, domain: Optional[str] = None, name: Optional[str] = None) -> List[DataProduct]: ...
    async def delete(self, id: UUID) -> bool: ...

class DataContractRepository(Protocol):
    async def get(self, id: UUID) -> DataContract: ...
    async def save(self, contract: DataContract) -> None: ...
    async def list(self, dp_id: Optional[str] = None) -> List[DataContract]: ...
    async def delete(self, id: UUID) -> bool: ...

# Legacy support for DataMeshService
class DataMeshRepository(Protocol):
    def create_data_product(self, dp: DataProduct) -> DataProduct: ...
    def get_data_product(self, dp_id: str) -> Optional[DataProduct]: ...
    def list_data_products(self, domain: str = None, name: str = None, version: str = None) -> List[DataProduct]: ...
    def update_data_product(self, dp: DataProduct) -> DataProduct: ...
    def delete_data_product(self, dp_id: str) -> bool: ...
    def create_data_contract(self, dc: DataContract) -> DataContract: ...
    def get_data_contract(self, dc_id: str) -> Optional[DataContract]: ...
    def list_data_contracts(self, dp_id: str = None) -> List[DataContract]: ...
    def update_data_contract(self, dc: DataContract) -> DataContract: ...
    def delete_data_contract(self, dc_id: str) -> bool: ...
    def flush(self) -> None: ...
