[pytest]
testpaths = cli/tests sdk/tests
pythonpath = cli sdk/src cli/dm/docker/open-data-mesh-ws
norecursedirs = .* venv .venv test_venv build dist
python_functions = test_* *_test
addopts = -v --tb=short